name: cbl_sentry_example
description: A simple command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  cbl:
    git:
      url: git@github.com:pieces-app/cbl-dart.git
      path: packages/cbl
  cbl_dart:
    git:
      url: git@github.com:pieces-app/cbl-dart.git
      path: packages/cbl_dart
  cbl_sentry:
    path: ..
  sentry: ^9.8.0
