name: cbl_sentry_example
description: A simple command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.6.0 <4.0.0"

resolution: workspace

dependencies:
  cbl: ^3.4.2+0
  cbl_dart: ^3.3.1
  cbl_sentry:
    path: ..
  sentry: ^9.8.0
